
url: "http://hlbleasdale.github.io"
baseurl: ""
title: Hope Bleasdale
author: Hope Bleasdale
email: sghbleas@liverpool.ac.uk
description: My first website

theme: jekyll-theme-cayman

header_pages:
   - index.md
   - PostgraduateEducation.md

collections: 
    Postgraduate Education:
        output: true
        permalink: "/PostgraduateEducation.md/:path"
